### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by bananarne** [ilammy/ftrace-hook#6]
i am not able to compile due to an incomplete definition of struct ftrace_ops

kernel 5.0.10

**Comment by ningyuv** [comment]
maybe your distribution not support ftrace

**Comment by ilammy** [comment]
I admin, I'm not doing a good job at maintaining this this in working order, but recent versions seems to do fine with stock Debian kernels. Please make sure that you have ftrace and kprobes enabled.

I don't to hunt down exact flag configuration, but here's what my kernel uses:

```
CONFIG_KPROBES=y
CONFIG_KPROBES_ON_FTRACE=y
CONFIG_HAVE_KPROBES=y
CONFIG_HAVE_KPROBES_ON_FTRACE=y
CONFIG_STM_SOURCE_FTRACE=m
# CONFIG_PSTORE_FTRACE is not set
CONFIG_HAVE_DYNAMIC_FTRACE=y
CONFIG_HAVE_DYNAMIC_FTRACE_WITH_REGS=y
CONFIG_HAVE_FTRACE_MCOUNT_RECORD=y
CONFIG_FTRACE=y
CONFIG_FTRACE_SYSCALLS=y
CONFIG_DYNAMIC_FTRACE=y
CONFIG_DYNAMIC_FTRACE_WITH_REGS=y
CONFIG_FTRACE_MCOUNT_RECORD=y
# CONFIG_FTRACE_STARTUP_TEST is not set
# CONFIG_KPROBES_SANITY_TEST is not set
# CONFIG_SAMPLE_KPROBES is not set
```

Please reopen the issue if it's still actual for you.
